name: melos_repostiory_sample5

packages:
  - apps/*
  - packages/**

scripts:
  analyze:
    exec: dart analyze .

  build_runner:
    run: dart run build_runner build -d
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: build_runner
